### ISSUE TITLE
nginx configuration

### ISSUE THREAD

**Issue by seastan** [mreishus/spades#308]
I'm attempting to deploy my fork of your repo using nginx. Have you been able to do this successfully? I see you have an nginx config file in frontend/nginx/nginx.conf.

I am a quite new at this, so I'm probably going about it all wrong, but this is what I have so far:

In `/etc/nginx/sites-available/mysite.com`:
```
upstream phoenix {
  server 127.0.0.1:4000 max_fails=5 fail_timeout=60s;
}

server {
  server_name mysite.com www.mysite.com;
  listen 80;

  location /be/ {
    allow all;

    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header X-Cluster-Client-Ip $remote_addr;
                      
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    proxy_pass http://phoenix;
  }

  location / {
    proxy_pass http://localhost:3000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }
}
```
After doing this, I also had to modify `/api` and `/api/v1`  in `router.ex` to  `/be/api` and `/be/api/v1` to route them to the backend.

With this, I am able to load the website, and it seems to be connecting to the backend, as I am able to create a game and have it show up in the list of games. However, when I try to enter a room, I get as far as rendering Room.tsx before it stops loading, presumably because the gameUI is null.

One error that I keep seeing in the console is:
```
WebSocket connection to 'ws://localhost:4000/socket/websocket?&vsn=2.0.0' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

Just curious if you have any troubleshooting tips.

**Comment by mreishus** [comment]
For running in production, I use docker. [build.sh](https://github.com/mreishus/spades/blob/master/build.sh) helps me build an image for both the frontend and backend. Then I run both images, and they both create webservers on their exposed sockets. The backend uses the built in phoenix webserver, and the frontend uses nginx with the config file you found ([dockerfile for frontend](https://github.com/mreishus/spades/blob/master/frontend/Dockerfile)).

The weird bit about the frontend dockerfile referencing a host called spades-backend-http is because I'm using kubernetes. The kubernetes config files I'm using are not published in this repository, I can if you would like, but it is a huge thing that you might not want to get into if you aren't already using it.

I have two main suggestions
* Try to use docker and docker-compose. I haven't written a docker compose file so you'll have to learn a little bit about how to make one so these two images can talk to each other, but it probably won't be that bad, and the only hardcoded hostname I can think of is the `spades-backend-http` in the nginx.conf.
* Go ahead and use nginx without docker, but first try to get it working without modifying the paths. IE, keep /be/ and /be/socket/ how they are; change as little of the existing nginx.conf in this repo as possible. Will probably only need to change the hostname in the proxy_pass lines and the root directory name. I think I needed everything in /be/ to be passed through, and everything else to load directly from the frontend.

**Comment by seastan** [comment]
I don't have any experience with docker, so I've been going at it the manual way. I ended up consulting an experienced developer to help with deployment. If you're curious, this is what the nginx server blocks look like now. The site is live, and things seem to work well. The only issue I still need to work out is that once you're actually in the game, refreshing the page will give a 404.

```
upstream phoenix {
  server 0.0.0.0:4000;
}

server {
  root /var/www/mysite.com/html;
  index index.html index.htm;

  server_name mysite.com www.mysite.com;

  location /be {
    rewrite ^/be/(.*)$ /$1 break;
    try_files $uri @proxy;
 }

  location / {
    try_files $uri @proxy $uri/ =404;
  }

  location @proxy {
    # include proxy_params;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_pass http://phoenix;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_http_version 1.1;
  }

  listen 443 ssl; # managed by Certbot
  ssl_certificate /etc/letsencrypt/live/mysite.com/fullchain.pem; # managed by Certbot
  ssl_certificate_key /etc/letsencrypt/live/mysite.com/privkey.pem; # managed by Certbot
  include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
  if ($host = www.mysite.com) {
      return 301 https://$host$request_uri;
  } # managed by Certbot
  
  listen 80;
  listen [::]:80;
  server_name mysite.com www.mysite.com;
  return 404; # managed by Certbot
}

```
