### ISSUE TITLE
how would this project get deployed?

### ISSUE THREAD

**Issue by dedmonies** [mreishus/spades#381]
was wondering how would you deploy this repo and how the frontend and backend would still be linked ....

**Comment by mreishus** [comment]
When I deployed it, I used kubernetes which is complex can be overkill for only one application. In general the steps should be
* Use ./build.sh to make docker images
* Run the backend and frontend images
* Make sure the backend image can connect to a database
* Make sure the frontend image can connect to the backend.
  * By default, it tries to look up a [hostname called "spades-backend-http" and contact that on port 4000](https://github.com/mreishus/spades/blob/3e06fa5c2415ff43258ec4c231f8d6c49c683fe0/frontend/nginx/nginx.conf#L20). I think I used kubernetes to make this hostname point to the backend container.

Off the top of my head, I don't know how to do this with docker, but the info should be out there, or you can also change the nginx.conf line, or maybe write to /etc/hosts when building the frontend image. [SO Link?](https://stackoverflow.com/questions/37242217/access-docker-container-from-host-using-containers-name/45071126#45071126). Maybe docker-compose makes this easy?

Something else you might want to check out is https://github.com/seastan/DragnCards , a fork of this project. Looks like it uses vagrant and it might have tweaked the whole setup, not really sure. 
I also uploaded my example kubernetes config but it probably won't be that useful because it's kubernetes and it's 4 years old. https://github.com/mreishus/spades/blob/master/example-k8s-config.txt

**Comment by killsforaliving** [comment]
Ummmm thanks I guess lol … it’s like you’re speaking Chinese (I’m a noob) but I’ll Figure it out …

**Comment by mreishus** [comment]
Well, I do feel this project ended up on the overcomplicated side. If I rewrote it again, I would probably do it all in phoenix live view with only one repository.  I'd say definitely stay away from kubernetes if you're a noob, but figuring out how to run two docker images and have them talk to each other could be a worthy goal in learning about sysadmin and networking.

**Comment by dedmonies** [comment]
so i created a docker image for the backend but when i run it i get this error" Invalid -name given to erl" , ive searched the net and haven't found a solution. You have any solutions ? thanks by the way ....
